---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocean-nvme
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocean-nvme
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocean-nvme
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocean-nvme
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocean-nvme
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocean-hdd
  resources:
    requests:
      storage: 2Ti