apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/version: "v1.18.2"
    app.kubernetes.io/managed-by: k3s-helm
spec:
  # The Helm repository URL
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.18.2

  # Target namespace and creation
  targetNamespace: cert-manager
  createNamespace: true

  # Values as per the install command
  valuesContent: |-
    crds:
      enabled: true