apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-cloudflare
spec:
  acme:
    # The ACME server URL. Let's Encrypt production endpoint:
    server: https://acme-v02.api.letsencrypt.org/directory
    # Reference to a Secret used to store the ACME account private key:
    privateKeySecretRef:
      name: letsencrypt-dns-cloudflare-account-key
    # Contact email for important account notifications:
    email: ncrmro@gmail.com
    solvers:
      - dns01:
          cloudflare:
            # Reference to a secret (see below) holding the Cloudflare API token:
            email: ncrmro@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token

---
# Example Kubernetes Secret for Cloudflare API Token
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-api-token-secret
#   namespace: cert-manager
# type: Opaque
# stringData:
#   api-token: ""