apiVersion: v1
kind: Namespace
metadata:
  name: pgo
  labels:
    name: pgo
---
# HelmChart Custom Resource Definition for installing pgo in k3s using an OCI Helm chart
# Documentation: https://rancher.com/docs/k3s/latest/en/helm/#deploying-helm-charts-using-helmchart-crd

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pgo
  namespace: kube-system       # 'kube-system' is commonly used for HelmChart CRDs in k3s
spec:
  chart: oci://registry.developers.crunchydata.com/crunchydata/pgo
  # Optionally specify a version (replace <version> if necessary)
  # version: <VERSION>
  # Optional: Specify custom values using 'valuesContent'
  # valuesContent: |-
  #   # Set your custom values here
  #   pgOperator:
  #     image:
  #       tag: latest
  #   ...
  targetNamespace: pgo         # Namespace where PGO will be deployed (choose as needed)
  # Optionally, set helm upgrade/install timeouts (seconds)
  # timeout: 600
  # Optional: Control the Helm release name (defaults to metadata.name)
  # releaseName: pgo
  # Optional: Retain release history if desired
  # disableHooks: false
  # Optional: Wait for jobs/pods (see k3s docs for available fields)
  # wait: true

  # kubernetes service account used for deployment (usually leave as default unless RBAC requires)
  # serviceAccount: default