name: 'Setup Tailscale'
description: 'Connect to Tailscale network via Headscale server'
inputs:
  authkey:
    description: 'Tailscale auth key (preferably ephemeral)'
    required: true
  timeout:
    description: 'Connection timeout in seconds'
    required: false
    default: '30'
  accept-routes:
    description: 'Accept subnet routes from other nodes'
    required: false
    default: 'true'
  accept-dns:
    description: 'Accept DNS configuration from Headscale'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install Tailscale
      shell: bash
      run: |
        # Download and install Tailscale
        curl -fsSL https://tailscale.com/install.sh | sh
        
        # Verify installation
        tailscale version
        
    - name: Connect to Tailscale Network
      shell: bash
      run: |
        # Build connection flags
        FLAGS="--authkey=${{ inputs.authkey }}"
        FLAGS="$FLAGS --login-server=https://mercury.ncrmro.com"
        FLAGS="$FLAGS --timeout=${{ inputs.timeout }}s"
        
        if [ "${{ inputs.accept-routes }}" = "true" ]; then
          FLAGS="$FLAGS --accept-routes"
        fi
        
        if [ "${{ inputs.accept-dns }}" = "true" ]; then
          FLAGS="$FLAGS --accept-dns"
        fi
        
        # Connect to network
        echo "Connecting to Tailscale network..."
        sudo tailscale up $FLAGS
        
    - name: Verify Connection
      shell: bash
      run: |
        echo "=== Tailscale Status ==="
        tailscale status
        
        echo ""
        echo "=== Tailscale IP Address ==="
        tailscale ip -4
        
        echo ""
        echo "=== Network Check ==="
        tailscale netcheck
        
        echo ""
        echo "=== DNS Resolution Test ==="
        # Test internal DNS resolution
        nslookup mercury || echo "Could not resolve mercury (this is normal if not in DNS)"
        
        echo ""
        echo "=== Connection Successful ==="